//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace try3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Date { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> Cost { get; set; }
        public int Category_id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
